### ISSUE TITLE
Update NPM dependencies from vsts-task-lib to azure-pipelines-task-lib

### ISSUE THREAD

**Issue by almmechanics** [chef-partners/azuredevops-chef#27]
I noticed that you're using `vsts-task-lib`, it might be worth updating the dependencies to `azure-pipelines-task-lib` to keep in sync with any potential breaking changes from Microsoft.

**Comment by stuartpreston** [comment]
@russellseymour

**Comment by russellseymour** [comment]
Yep agreed. WIll try and put it in the next release.

The issue with this is that anyone that already hs a YAML file for their pipeline will find their builds break as the names have changed.

**Comment by russellseymour** [comment]
All tasks now use the `azure-pipelines-task-lib`.
