### ISSUE TITLE
[FEATURE] Add documentation on YAML schema for Azure Pipelines

### ISSUE THREAD

**Issue by ehanlon** [chef-partners/azuredevops-chef#28]
Would love to get some documentation in the wiki on how to implement the tasks via `azure-pipelines.yml`.

**Comment by russellseymour** [comment]
@ehanlon Good call, will update the docs to reflect this

As I am sure you know you can build the pipeline manually and then export the YAML from your pipeline. This will at least give you the names of the tasks that you need to set.

I know that the tasks are still prefixed with `vsts-`. This is something that I will look to change as well.

**Comment by russellseymour** [comment]
I apologise for not getting back to you sooner on this.

I have added a page to the documentation regarding YAML pipeline files - https://chef-partners.github.io/azuredevops-habitat/azdo-pipeline.html.

**Comment by russellseymour** [comment]
Sorry @ehanlon , was getting confused between the two repos for our extensions
I have not added YAML docs to the Chef Extension yet. I will open this issue again as a reminder.

**Comment by Mukund-UBS** [comment]
Hi @russellseymour ,

I am creating two pipeline - 

**1. The first is for scanning the content provided by chef in profile for inspec. 
2. Another build pipeline for cookbook remediation.** 

So, do we have such documents for the above two as well? 

Looking for a quick reply, as I have some delivery. 

Regards
Mukund

**Comment by russellseymour** [comment]
Added documentation to show the fully qualified task names to be used in an Azure DevOps pipeline. This documentation also contains a simple example of how to the use the tasks.

https://github.com/chef-partners/azuredevops-chef/wiki/azure-devops-pipelines

**Comment by Mukund-UBS** [comment]
Hi, @russellseymour , one more thing, how can i run Automate i mean from Chef node by using chef client if i want to run audit cookbook, how can i do via azure devops pipeline?
